version: "3.9"

services:

  vue-sandbox-web:
    container_name: vue-sandbox-web
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    entrypoint: ["nginx-debug", "-g", "daemon off;"] 
    networks:
      vue-sandbox-network:
        aliases:
          - vue-sandbox.com

networks:
  vue-sandbox-network: